name       : polybar
version    : 3.0.5
release    : 14
source     :
    - git|https://github.com/jaagr/polybar.git : 3.0.5
license    : MIT
component  : system.utils
summary    : A fast and easy-to-use status bar
description: |
    A fast and easy-to-use status bar
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo-fc)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-proto)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcomposite)
    - pkgconfig(xft)
    - i3-devel
    - libboost-devel
    - wireless-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-curlbuild-include.patch
    %cmake .
build      : |
    %make
    %make userconfig
install    : |
    %make_install
