name       : polybar
version    : 2.4.6
release    : 4
source     :
    - git|https://github.com/jaagr/polybar.git : 2.4.6
license    : MIT
component  : system.utils
summary    : A fast and easy-to-use status bar
description: |
    A fast and easy-to-use status bar
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-proto)
    - pkgconfig(xcb-util)
    - pkgconfig(xcomposite)
    - pkgconfig(xft)
    - i3-devel
    - libboost-devel
    - wireless-tools-devel
setup      : |
    %cmake .
build      : |
    %make
    %make userconfig
install    : |
    %make_install
