name       : polybar
version    : 3.5.7
release    : 36
source     :
    - git|https://github.com/jaagr/polybar.git : 3.5.7
license    : MIT
component  : system.utils
summary    : A fast and easy-to-use status bar
description: |
    A fast and easy-to-use status bar
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo-fc)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(libpulse)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-proto)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcomposite)
    - pkgconfig(xft)
    - i3-devel
    - libboost-devel
    - wireless-tools-devel
rundeps    :
    - python3
setup      : |
    %cmake .
build      : |
    %make
    %make userconfig
install    : |
    %make_install
