name       : polybar
version    : 3.6.3
release    : 38
source     :
    - git|https://github.com/polybar/polybar.git : 3.6.3
license    : MIT
component  : system.utils
summary    : A fast and easy-to-use status bar
description: |
    A fast and easy-to-use status bar
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo-fc)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(libpulse)
    - pkgconfig(libuv)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-proto)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcomposite)
    - pkgconfig(xft)
    - i3-devel
    - libboost-devel
    - python-sphinx
    - wireless-tools-devel
rundeps    :
    - python3
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
